# Generated by Django 4.1.2 on 2022-11-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='first_namr',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='user_name',
        ),
        migrations.AddField(
            model_name='signup',
            name='Gender1',
            field=models.CharField(default='', max_length=30),
        ),
    ]
