# Generated by Django 4.1.2 on 2022-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0002_rename_first_namr_signup_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Gender1',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
