# Generated by Django 4.1.2 on 2022-11-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0003_signup_name_alter_signup_gender1'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productid', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, default='draftname', max_length=100)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('des', models.CharField(blank=True, default='draftname', max_length=100)),
                ('tag', models.CharField(blank=True, default='draftname', max_length=100)),
                ('courseimg', models.CharField(max_length=100)),
            ],
        ),
    ]
