# Generated by Django 4.1.2 on 2022-11-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='courseimg',
            new_name='img',
        ),
    ]
